# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --add-opens=java.base/java.io=ALL-UNNAMED

# AndroidX package structure
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Enable Gradle build cache
org.gradle.caching=true

# Enable parallel builds
org.gradle.parallel=true

# Java toolchain version
org.gradle.java.home=C\:\\Program Files\\Android\\Android Studio\\jbr
org.gradle.configuration-cache=true
